# action.yml
name: 'easy configurable php-cs-fixer'
branding:
  icon: 'check'  
  color: 'green'
description: 'An easy way to run a configurable php-cs-fixer on your project without adding it as a dependency.'
inputs:
  other-cmds:
    description: 'Add some configs'
    required: false
    default: '--dry-run --diff --using-cache=no --diff-format udiff'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.other-cmds }}